file_format: "1"
id: redox
name: Redox
type: shield
url: https://github.com/jimmerricks/swoop
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - redox_left
  - redox_right
